services:
  backend:
    build: ./backend
    image: welhome-backend:latest
    environment:
      DB_PATH: /data/properties.db
      CORS_ORIGINS: "http://localhost:8080"
    volumes:
      - welhome_db:/data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 6

  web:
    build: ./frontend
    image: welhome-frontend:latest
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost/ >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  welhome_db: {}
